### ISSUE TITLE
LSOS v1.2 can't verify sketch

### ISSUE THREAD

**Issue by DJWing79** [neskweek/LightSaberOS#19] opened 2016-07-15 03:25 UTC
Using Arduino IDE to compile the newest version and I get the following error

`Arduino: 1.6.9 (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\Damien\Downloads\LightSaberOS\LightSaberOS\LightSaberOS.ino: In function 'void loop()':

LightSaberOS:1099: error: duplicate case value

```
case 2: // BLADE MAIN COLOR

^
```

LightSaberOS:1000: error: previously used here

```
case 2: // BLADE MAIN COLOR

^
```

LightSaberOS:1118: error: duplicate case value

```
case 3: //BLADE CLASH COLOR

^
```

LightSaberOS:1022: error: previously used here

```
case 3: //BLADE CLASH COLOR

^
```

LightSaberOS:1149: error: 'struct StoreStruct' has no member named 'soundFontColorPreset'

```
 storage.soundFontColorPreset[storage.soundFont][0] =

         ^
```

LightSaberOS:1151: error: 'struct StoreStruct' has no member named 'soundFontColorPreset'

```
 storage.soundFontColorPreset[storage.soundFont][1] =

         ^
```

LightSaberOS:1357: error: too few arguments to function 'void lightOff(uint8_t*)'

```
lightOff();

         ^
```

In file included from C:\Users\Damien\Downloads\LightSaberOS\LightSaberOS\LightSaberOS.ino:24:0:

sketch\Light.h:40:6: note: declared here

 void lightOff(uint8_t ledPins[]);

```
  ^
```

exit status 1
duplicate case value

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by jbkuma** [comment] 2016-07-15 04:08
having the same issue.

**Comment by neskweek** [comment] 2016-07-15 09:04
Hello
Please use version 1.6.5-R5

**Comment by jbkuma** [comment] 2016-07-15 11:48
I installed to 1.6.5-r5 yesterday and double checked this morning.  Still getting the same error.

**Comment by neskweek** [comment] 2016-07-15 11:59
Yeah, My bad.... Sorry

I missed an error in RGB blade code.
This should be corrected in V1.2.2 I just uploaded.

**Comment by jbkuma** [comment] 2016-07-15 12:43
It checks out now, thanks!

**Comment by neskweek** [comment] 2016-07-15 12:51
You're welcome 
Since I can't test RGB blade code, please tell me if everything is working correctly ;)

**Comment by DJWing79** [comment] 2016-07-15 14:57
So it can upload but now the config mode has three new menus it didn't have before, I get power off effect, power off effect, and flicker effect. No matter what I do, I can't change the colors. I am using luxeon and myowncolors with colors set to 48

**Comment by neskweek** [comment] 2016-07-15 16:26
That shouldn't be the case.
Are you sure you commented #define LEDSTRING ?
did you cleared previous files in your directory ?

I can't test fire RGB blade, but I can test sound and menu on RGB code, and I don't reproduce this here.

**Comment by DJWing79** [comment] 2016-07-15 16:43
/facepalm

yup, forgot that part, will test it tonight.

**Comment by neskweek** [comment] 2016-07-15 20:46
Does this work ok now ? :)

if so I'll close this one ;)

**Comment by DJWing79** [comment] 2016-07-16 03:28
So I got the ability to change colors, but only 3 colors. I have FIXED_RANGE_COLORS commented out, but it seems to be stuck on the 3 colors only and won't mix them. Its almost as if the getColor function isn't being called

**Comment by DJWing79** [comment] 2016-07-16 05:15
ok for sheer shits and giggles, I commented MY_OWN_COLORS and uncommented FIXED_RANGE_COLORS and now it works with mixing, weird....it's completely reversed from the previous version.

**Closed as completed** 2016-07-25 19:11 UTC
Labels: bug
